version: "3.7"
services:

  backend:
    build: backend
    ports: 
      - 3001:3001
    links:
      - db:mysql
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
  
  frontend:
    build: frontend
    ports: 
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: "mysql"
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: "compsecproject"