version: "3.7"
services:

  backend:
    build: backend
    ports: 
      - "${BACKEND_SERVICE_PORT}:${BACKEND_SERVICE_PORT}"
    links:
      - db:mysql
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
  
  frontend:
    build: frontend
    ports: 
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: "mysql"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment: 
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"