version: "3.7"

services:

  backend:
    build: backend
    ports: 
      - ${BACKEND_SERVICE_PORT}:${BACKEND_SERVICE_PORT}
    links:
      - db:mysql
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
  
  frontend:
    build: frontend
    ports: 
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BACKEND_ENDPOINT=localhost
  db:
    # build: mysql
    env_file:
      - ./backend/.env
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: "mysql"
    volumes:
      - ./mysql/dump:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment: 
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_TCP_PORT: ${DB_PORT}