version: "3.7"
services:
  app:
    build: .
    ports: 
      - "${BACKEND_SERVICE_PORT}:${BACKEND_SERVICE_PORT}"
    links:
      - db:mysql
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: "mysql"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment: 
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"