version: "3.7"
services:
  app:
    build: .
    ports: 
      - "3001:3001"
    links:
      - db:mysql
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: "mysql"
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"